name: kyouen
description: "Check whether it is Kyouen."
version: 0.0.1
homepage: https://github.com/noboru-i/kyouen_dart
repository: https://github.com/noboru-i/kyouen_dart

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies: null

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.5
